# Generated by Django 5.2.4 on 2025-07-24 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolo', models.IntegerField()),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hrac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('alance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hraci', to='aliance.aliance')),
            ],
        ),
        migrations.CreateModel(
            name='Zeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('odehrana_kola', models.IntegerField()),
                ('volna_kola', models.IntegerField()),
                ('zasobnik_kola', models.IntegerField()),
                ('ali_forum', models.CharField(max_length=10)),
                ('logout', models.CharField(max_length=10)),
                ('hrac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zeme', to='aliance.hrac')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aliance.snapshot')),
            ],
        ),
        migrations.CreateModel(
            name='ZemeAbilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zkusennosti_armady', models.IntegerField()),
                ('hodnost', models.IntegerField()),
                ('zkusennosti_vek', models.IntegerField()),
                ('sesvacenost', models.CharField(max_length=10)),
                ('operaci_rozvedky', models.IntegerField()),
                ('embargo_hlas', models.IntegerField()),
                ('spokojenost', models.CharField(max_length=10)),
                ('zeme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aliance.zeme')),
            ],
        ),
        migrations.CreateModel(
            name='ZemeBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vesnice', models.CharField(max_length=10)),
                ('farmy', models.CharField(max_length=10)),
                ('laboratore', models.CharField(max_length=10)),
                ('tovarny', models.CharField(max_length=10)),
                ('kasarny', models.CharField(max_length=10)),
                ('elektrarny', models.CharField(max_length=10)),
                ('vojenske_zakladny', models.CharField(max_length=10)),
                ('penize', models.CharField(max_length=10)),
                ('max_hospodarskych', models.CharField(max_length=10)),
                ('max_vojenskych', models.CharField(max_length=10)),
                ('efekt_hospodarskych', models.CharField(max_length=10)),
                ('utok', models.CharField(max_length=10)),
                ('obrana', models.CharField(max_length=10)),
                ('kolonizace', models.CharField(max_length=10)),
                ('zoldy', models.CharField(max_length=10)),
                ('zeme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aliance.zeme')),
            ],
        ),
        migrations.CreateModel(
            name='ZemeBuildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rozloha', models.FloatField()),
                ('vesnice', models.IntegerField()),
                ('mesta', models.IntegerField()),
                ('obchodni_zony', models.IntegerField()),
                ('farmy', models.IntegerField()),
                ('laboratore', models.FloatField()),
                ('tovarny', models.FloatField()),
                ('kasarny', models.FloatField()),
                ('elektrarny', models.FloatField()),
                ('zabavních_stredisek', models.FloatField()),
                ('vojenskych_zakladen', models.FloatField()),
                ('stavebni_firmy', models.IntegerField()),
                ('nezastavene_uzemi', models.FloatField()),
                ('ruiny', models.FloatField()),
                ('zeme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aliance.zeme')),
            ],
        ),
        migrations.CreateModel(
            name='ZemeComodits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penez', models.FloatField()),
                ('jidla', models.FloatField()),
                ('energie', models.FloatField()),
                ('na_trhu', models.IntegerField()),
                ('obyvatel', models.FloatField()),
                ('zeme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aliance.zeme')),
            ],
        ),
        migrations.CreateModel(
            name='ZemeEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rozvoj_zacatek', models.CharField(max_length=10)),
                ('hospodarska_pomoc', models.CharField(max_length=10)),
                ('dostal_hp', models.IntegerField()),
                ('poslal_hp', models.IntegerField()),
                ('humanitarni_pomoc', models.CharField(max_length=10)),
                ('do_pokladny', models.FloatField(max_length=10)),
                ('z_pokladny', models.FloatField()),
                ('zeme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aliance.zeme')),
            ],
        ),
        migrations.CreateModel(
            name='ZemeOthers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vesmir', models.FloatField(max_length=10)),
                ('utopie_spokojenost', models.FloatField()),
                ('android', models.CharField(max_length=10)),
                ('ufo_sance', models.CharField(max_length=10)),
                ('zeme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aliance.zeme')),
            ],
        ),
        migrations.CreateModel(
            name='ZemePrestige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestiz', models.IntegerField()),
                ('vojaku', models.IntegerField()),
                ('tanku', models.FloatField()),
                ('stihacek', models.FloatField()),
                ('bunkru', models.FloatField()),
                ('mechu', models.IntegerField()),
                ('agentu', models.IntegerField()),
                ('zeme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aliance.zeme')),
            ],
        ),
        migrations.CreateModel(
            name='ZemeProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prirustek_penez', models.IntegerField()),
                ('prirustek_jidla', models.IntegerField()),
                ('prirustek_energie', models.IntegerField()),
                ('prirustek_vojaku', models.IntegerField()),
                ('prirustek_dilu_jednotek', models.IntegerField()),
                ('prirustek_technologii', models.IntegerField()),
                ('zeme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aliance.zeme')),
            ],
        ),
        migrations.CreateModel(
            name='ZemeRakets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konvencnich', models.IntegerField()),
                ('bio', models.IntegerField()),
                ('emp', models.IntegerField()),
                ('nuklearnich', models.IntegerField()),
                ('zeme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aliance.zeme')),
            ],
        ),
        migrations.CreateModel(
            name='ZemeTechnologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospodarskych_celkem', models.FloatField()),
                ('rychlost_stavby', models.FloatField()),
                ('obchod', models.FloatField()),
                ('hustota_zalidneni', models.FloatField()),
                ('zemedelstvi', models.FloatField()),
                ('automatizace_tovaren', models.FloatField()),
                ('energie', models.FloatField()),
                ('vojenskych_celkem', models.IntegerField()),
                ('sila_zbrani', models.IntegerField()),
                ('domaci_trh', models.FloatField()),
                ('vyvoj_raket', models.FloatField()),
                ('protiraketova_obrana', models.FloatField()),
                ('sila_rozvedky', models.IntegerField()),
                ('vyzkum_vesmiru', models.IntegerField()),
                ('zeme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aliance.zeme')),
            ],
        ),
    ]
