
from django.db import models

class Aliance(models.Model):
    label = models.CharField(max_length=100)
    
    def __str__(self):
        return self.label

class Hrac(models.Model):
    name = models.CharField(max_length=100)
    number = models.IntegerField()
    alance = models.ForeignKey(Aliance, related_name='hraci', on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

class Zeme(models.Model):
    hrac = models.ForeignKey(Hrac, on_delete=models.CASCADE, related_name='zeme')
    name = models.CharField(max_length=100)
    snapshot = models.ForeignKey(Snapshot, on_delete=models.CASCADE)
    number = models.IntegerField()
    prestiz_k = models.IntegerField()
    vojaku_k = models.IntegerField()
    tanku_k  = models.FloatField()
    stihacek_k = models.FloatField()
    bunkru_k = models.FloatField()
    mechu_k = models.IntegerField()
    agentu = models.IntegerField()
    operaci_rozvedky = models.IntegerField()
    konvencnich = models.IntegerField()
    bio = models.IntegerField()
    emp = models.IntegerField()
    nuklearnich = models.IntegerField()
    zkusennost_armady_k = models.IntegerField()
    hodnost = models.IntegerField()
    zkusennost_vek_k = models.IntegerField()
    sesvacenost = models.CharField(max_length=10)
    t_hospod_celkem_k = models.FloatField()
    t_rychlost_k = models.FloatField()
    t_obchod_k = models.FloatField()
    t_hustota_k = models.FloatField()
    t_zemedel_k = models.FloatField()
    t_tovaren_k = models.FloatField()
    t_energie_k = models.FloatField()
    t_vojen_celkem_k = models.IntegerField()
    t_silazb_k = models.IntegerField()
    t_domtrh_k = models.FloatField()
    t_rakety_k = models.FloatField()
    t_protiraket_k = models.FloatField()
    t_rozved_k = models.IntegerField()
    t_vyzkum_k = models.IntegerField()
    obyvatel_m = models.FloatField()
    penez_m = models.FloatField()
    jidla_k = models.FloatField()
    energie_k = models.FloatField()
    spokojenost = models.CharField(max_length=10)
    na_trhu = models.IntegerField()
    prirustek_penez_k = models.IntegerField()
    prirustek_jidla = models.IntegerField()
    prirustek_energie = models.IntegerField()
    prirustek_vojaku = models.IntegerField()
    prirustek_dilu_jedn = models.IntegerField()
    prirustek_technologii = models.IntegerField()
    rozloha_k = models.FloatField()
    vesnice_k = models.IntegerField()
    mesta_k = models.IntegerField()
    obchod_z_k = models.IntegerField()
    farmy_k = models.IntegerField()
    laboratore_k = models.FloatField()
    tovarny_k = models.FloatField()
    kasarny_k = models.FloatField()
    elektrarny_k = models.FloatField()
    zabavnych_stredisek_k = models.FloatField()
    voj_zakladen_k = models.FloatField()
    stavebni_firmy = models.IntegerField()
    nezastavene_k = models.FloatField()
    ruiny_k = models.FloatField()
    b_vesnice = models.CharField(max_length=10)
    b_farmy = models.CharField(max_length=10)
    b_laboratore = models.CharField(max_length=10)
    b_tovarny = models.CharField(max_length=10)
    b_kasarny = models.CharField(max_length=10)
    b_elektrarny = models.CharField(max_length=10)
    b_voj_zakladny = models.CharField(max_length=10)
    b_penize = models.CharField(max_length=10)
    b_max_hospod = models.CharField(max_length=10)
    b_max_vojen = models.CharField(max_length=10)
    b_efekt_hospod = models.CharField(max_length=10)
    b_utok = models.CharField(max_length=10)
    b_obrana = models.CharField(max_length=10)
    b_kolonizace = models.CharField(max_length=10)
    b_zoldy = models.CharField(max_length=10)
    logout = models.CharField(max_length=10)
    rozvoj_zacatek = models.CharField(max_length=10)
    hosp_pomoc = models.CharField(max_length=10)
    dostal_hp = models.IntegerField()
    poslal_hp = models.IntegerField()
    hum_pomoc = models.CharField(max_length=10)
    ali_forum = models.CharField(max_length=10)
    do_poklad = models.FloatField(max_length=10)
    z_poklad_m = models.FloatField()
    vesmir = models.FloatField(max_length=10)
    utop_spok_k = models.FloatField()
    android = models.CharField(max_length=10)
    ufo_sance = models.CharField(max_length=10)
    embargo_hlas = models.IntegerField()
    odehrana_kola = models.IntegerField()
    volna_kola = models.IntegerField()
    zasobnik_kola = models.IntegerField()

    def __str__(self):
        return f"{self.name} ({self.number})"

class Snapshot(models.Model):
    kolo = models.IntegerField()
    created_ad = models.DateTimeField(auto_now_add=True)